import { GenreType } from '@/utils/type';

export const GENREINFO: GenreType[] = [
  {
    id: 1,
    short_name: 'act',
    technical_name: 'action',
    translation: '액션',
    slug: 'aegsyeon',
  },
  {
    id: 2,
    short_name: 'ani',
    technical_name: 'animation',
    translation: '애니메이션',
    slug: 'aenimeisyeon',
  },
  {
    id: 3,
    short_name: 'cmy',
    technical_name: 'comedy',
    translation: '코미디',
    slug: 'komidi',
  },
  {
    id: 4,
    short_name: 'crm',
    technical_name: 'crime',
    translation: '범죄',
    slug: 'beomjoe',
  },
  {
    id: 5,
    short_name: 'doc',
    technical_name: 'documentation',
    translation: '다큐멘터리',
    slug: 'dakyumenteori',
  },
  {
    id: 6,
    short_name: 'drm',
    technical_name: 'drama',
    translation: '드라마',
    slug: 'deurama',
  },
  {
    id: 7,
    short_name: 'fnt',
    technical_name: 'fantasy',
    translation: '판타지',
    slug: 'pantaji',
  },
  {
    id: 8,
    short_name: 'hst',
    technical_name: 'history',
    translation: '역사',
    slug: 'yeogsa',
  },
  {
    id: 9,
    short_name: 'hrr',
    technical_name: 'horror',
    translation: '공포',
    slug: 'gongpo',
  },
  {
    id: 10,
    short_name: 'fml',
    technical_name: 'family',
    translation: '가족',
    slug: 'gajog',
  },
  {
    id: 11,
    short_name: 'msc',
    technical_name: 'music',
    translation: '음악',
    slug: 'eumag',
  },
  {
    id: 12,
    short_name: 'trl',
    technical_name: 'thriller',
    translation: '스릴러',
    slug: 'seurilreo',
  },
  {
    id: 13,
    short_name: 'rma',
    technical_name: 'romance',
    translation: '로맨스',
    slug: 'romaenseu',
  },
  {
    id: 14,
    short_name: 'scf',
    technical_name: 'scifi',
    translation: 'SF',
    slug: 'sf',
  },
  {
    id: 15,
    short_name: 'spt',
    technical_name: 'sport',
    translation: '스포츠',
    slug: 'seupoceu',
  },
  {
    id: 16,
    short_name: 'war',
    technical_name: 'war',
    translation: '전쟁',
    slug: 'jeonjaeng',
  },
  {
    id: 17,
    short_name: 'wsn',
    technical_name: 'western',
    translation: '서부',
    slug: 'seobu',
  },
  {
    id: 23,
    short_name: 'rly',
    technical_name: 'reality',
    translation: 'Reality TV',
    slug: 'reality-tv',
  },
  {
    id: 18,
    short_name: 'eur',
    technical_name: 'european',
    translation: 'Made in Europe',
    slug: 'made-in-europe',
  },
];

export const PLATFORMINFO = [
  {
    id: 8,
    name: 'Netflix',
    monetization_types: ['flatrate'],
    iconURL: 'https://images.justwatch.com/icon/207360008/s100',
  },
  {
    id: 119,
    name: 'Amazon Prime Video',
    monetization_types: ['flatrate'],
    iconURL: 'https://images.justwatch.com/icon/52449861/s100',
  },
  {
    id: 356,
    name: 'wavve',
    monetization_types: ['flatrate', 'rent', 'buy'],
    iconURL: 'https://images.justwatch.com/icon/155655742/s100',
  },
  {
    id: 97,
    name: 'Watcha',
    monetization_types: ['flatrate'],
    iconURL: 'https://images.justwatch.com/icon/2538290/s100',
    icon_blur_hash: 'KPGlL@004n00%Mxu9Fofxu',
    slug: 'watcha',
  },
  {
    id: 96,
    name: 'Naver Store',
    monetization_types: ['buy', 'rent'],
    iconURL: 'https://images.justwatch.com/icon/2538289/s100',
  },
  {
    id: 3,
    name: 'Google Play Movies',
    monetization_types: ['rent', 'buy'],
    iconURL: 'https://images.justwatch.com/icon/169478387/s100',
  },
  {
    id: 11,
    name: 'Mubi',
    monetization_types: ['flatrate', 'rent'],
    iconURL: 'https://images.justwatch.com/icon/164970114/s100',
  },
  {
    id: 100,
    name: 'GuideDoc',
    monetization_types: ['flatrate'],
    iconURL: 'https://images.justwatch.com/icon/2625277/s100',
  },
  {
    id: 101,
    name: 'Daum',
    monetization_types: ['cinema'],
    iconURL: 'https://images.justwatch.com/icon/2655283/s100',
  },
  {
    id: 98,
    name: 'Megabox',
    monetization_types: ['cinema'],
    iconURL: 'https://images.justwatch.com/icon/2539917/s100',
  },
  {
    id: 283,
    name: 'Crunchyroll',
    monetization_types: ['flatrate'],
    iconURL: 'https://images.justwatch.com/icon/127445869/s100',
  },
  {
    id: 190,
    name: 'Curiosity Stream',
    monetization_types: ['flatrate'],
    iconURL: 'https://images.justwatch.com/icon/48600036/s100',
  },
  {
    id: 521,
    name: 'Spamflix',
    monetization_types: ['free', 'rent'],
    iconURL: 'https://images.justwatch.com/icon/240831409/s100',
  },
  {
    id: 475,
    name: 'DOCSVILLE',
    monetization_types: ['flatrate'],
    iconURL: 'https://images.justwatch.com/icon/208148387/s100',
  },
  {
    id: 495,
    name: 'CGood TV',
    monetization_types: ['free'],
    iconURL: 'https://images.justwatch.com/icon/208864843/s100',
  },
  {
    name: 'Disney Plus',
    id: 337,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/147638351/s100',
  },
  {
    name: 'Apple TV Plus',
    id: 350,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/152862153/s100',
  },
  {
    name: 'Plex',
    id: 538,
    monetizationTypes: ['FREE'],
    iconURL: 'https://images.justwatch.com/icon/301832745/s100',
  },
  {
    name: 'WOW Presents Plus',
    id: 546,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/243229654/s100',
  },
  {
    name: 'Magellan TV',
    id: 551,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/243233518/s100',
  },
  {
    name: 'BroadwayHD',
    id: 554,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/243239329/s100',
  },
  {
    name: 'Filmzie',
    id: 559,
    monetizationTypes: ['ADS'],
    iconURL: 'https://images.justwatch.com/icon/269433194/s100',
  },
  {
    name: 'Dekkoo',
    id: 444,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/202068207/s100',
  },
  {
    name: 'True Story',
    id: 567,
    monetizationTypes: ['FLATRATE', 'RENT'],
    iconURL: 'https://images.justwatch.com/icon/244289819/s100',
  },
  {
    name: 'DocAlliance Films',
    id: 569,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/244290074/s100',
  },
  {
    name: 'Hoichoi',
    id: 315,
    monetizationTypes: ['FREE'],
    iconURL: 'https://images.justwatch.com/icon/141253805/s100',
  },
  {
    name: 'Eventive',
    id: 677,
    monetizationTypes: ['RENT', 'FREE'],
    iconURL: 'https://images.justwatch.com/icon/258768419/s100',
  },
  {
    name: 'Cultpix',
    id: 692,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/264459628/s100',
  },
  {
    name: 'FilmBox+',
    id: 701,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/269959825/s100',
  },
  {
    name: 'Takflix',
    id: 1771,
    monetizationTypes: ['BUY', 'FREE'],
    iconURL: 'https://images.justwatch.com/icon/300757493/s100',
  },
  {
    name: 'Sun Nxt',
    id: 309,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/138047862/s100',
  },
  {
    name: 'Classix',
    id: 445,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/202068388/s100',
  },
  {
    name: 'Netflix basic with Ads',
    id: 1796,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/301462744/s100',
  },
  {
    name: 'TVING',
    id: 1883,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/304712515/s100',
  },
  {
    name: 'SPOTV NOW',
    id: 1879,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/304712218/s100',
  },
  {
    name: 'Coupang Play',
    id: 1881,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/304712363/s100',
  },
  {
    name: 'OneFootball',
    id: 1820,
    monetizationTypes: ['FREE'],
    iconURL: 'https://images.justwatch.com/icon/301743701/s100',
  },
  {
    name: 'NHL TV',
    id: 1843,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/302623129/s100',
  },
  {
    name: 'Tennis TV',
    id: 1863,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/304140196/s100',
  },
  {
    name: 'WTA TV',
    id: 1864,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/304140342/s100',
  },
  {
    name: 'BLAST.tv',
    id: 1908,
    monetizationTypes: ['FREE'],
    iconURL: 'https://images.justwatch.com/icon/305250213/s100',
  },
  {
    name: 'YouTube Sports',
    id: 1789,
    monetizationTypes: ['FREE', 'ADS'],
    iconURL: 'https://images.justwatch.com/icon/59562423/s100',
  },
  {
    name: 'The FA Player',
    id: 1813,
    monetizationTypes: ['FREE'],
    iconURL: 'https://images.justwatch.com/icon/301624576/s100',
  },
  {
    name: 'NWSL',
    id: 1915,
    monetizationTypes: ['FREE'],
    iconURL: 'https://images.justwatch.com/icon/305712691/s100',
  },
  {
    name: 'UEFA tv',
    id: 1886,
    monetizationTypes: ['ADS', 'FREE'],
    iconURL: 'https://images.justwatch.com/icon/304800674/s100',
  },
  {
    name: 'MLS Season Pass',
    id: 1851,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/303372959/s100',
  },
  {
    name: 'KBS',
    id: 1936,
    monetizationTypes: ['FREE'],
    iconURL: 'https://images.justwatch.com/icon/306598677/s100',
  },
  {
    name: 'SBS',
    id: 1935,
    monetizationTypes: ['FLATRATE', 'FREE'],
    iconURL: 'https://images.justwatch.com/icon/30659867/s100',
  },
  {
    name: 'MBC',
    id: 1938,
    monetizationTypes: ['FREE', 'ADS'],
    iconURL: 'https://images.justwatch.com/icon/306611855/s100',
  },
  {
    name: 'DAZN NFL Game Pass',
    id: 1942,
    monetizationTypes: ['FLATRATE'],
    iconURL: 'https://images.justwatch.com/icon/30728693/s100',
  },
];

export const POSTERTITLEURL = `https://apis.justwatch.com/content/titles/ko_KR/popular?body=%7B%22fields%22:[%22id%22,%22title%22,%22full_path%22,%22poster%22,%22object_type%22],%22content_types%22:[%22movie%22],%22monetization_types%22:[%22ads%22,%22buy%22,%22flatrate%22,%22rent%22,%22free%22],%22page%22:40,%22page_size%22:40,%22matching_offers_only%22:false%7D`;

export const PAGECONTENTCOUNT = 30;
