const GENREINFO = [
  {
    id: 1,
    short_name: 'act',
    technical_name: 'action',
    translation: '액션',
    slug: 'aegsyeon',
  },
  {
    id: 2,
    short_name: 'ani',
    technical_name: 'animation',
    translation: '애니메이션',
    slug: 'aenimeisyeon',
  },
  {
    id: 3,
    short_name: 'cmy',
    technical_name: 'comedy',
    translation: '코미디',
    slug: 'komidi',
  },
  {
    id: 4,
    short_name: 'crm',
    technical_name: 'crime',
    translation: '범죄',
    slug: 'beomjoe',
  },
  {
    id: 5,
    short_name: 'doc',
    technical_name: 'documentation',
    translation: '다큐멘터리',
    slug: 'dakyumenteori',
  },
  {
    id: 6,
    short_name: 'drm',
    technical_name: 'drama',
    translation: '드라마',
    slug: 'deurama',
  },
  {
    id: 7,
    short_name: 'fnt',
    technical_name: 'fantasy',
    translation: '판타지',
    slug: 'pantaji',
  },
  {
    id: 8,
    short_name: 'hst',
    technical_name: 'history',
    translation: '역사',
    slug: 'yeogsa',
  },
  {
    id: 9,
    short_name: 'hrr',
    technical_name: 'horror',
    translation: '공포',
    slug: 'gongpo',
  },
  {
    id: 10,
    short_name: 'fml',
    technical_name: 'family',
    translation: '가족',
    slug: 'gajog',
  },
  {
    id: 11,
    short_name: 'msc',
    technical_name: 'music',
    translation: '음악',
    slug: 'eumag',
  },
  {
    id: 12,
    short_name: 'trl',
    technical_name: 'thriller',
    translation: '스릴러',
    slug: 'seurilreo',
  },
  {
    id: 13,
    short_name: 'rma',
    technical_name: 'romance',
    translation: '로맨스',
    slug: 'romaenseu',
  },
  {
    id: 14,
    short_name: 'scf',
    technical_name: 'scifi',
    translation: 'SF',
    slug: 'sf',
  },
  {
    id: 15,
    short_name: 'spt',
    technical_name: 'sport',
    translation: '스포츠',
    slug: 'seupoceu',
  },
  {
    id: 16,
    short_name: 'war',
    technical_name: 'war',
    translation: '전쟁',
    slug: 'jeonjaeng',
  },
  {
    id: 17,
    short_name: 'wsn',
    technical_name: 'western',
    translation: '서부',
    slug: 'seobu',
  },
  {
    id: 23,
    short_name: 'rly',
    technical_name: 'reality',
    translation: 'Reality TV',
    slug: 'reality-tv',
  },
  {
    id: 18,
    short_name: 'eur',
    technical_name: 'european',
    translation: 'Made in Europe',
    slug: 'made-in-europe',
  },
];

export const PLATFORMINFO = [
  {
    id: 8,
    name: 'Netflix',
    monetization_types: ['flatrate'],
    icon_url: 'https://images.justwatch.com/icon/207360008/s100',
  },
  {
    id: 119,
    name: 'Amazon Prime Video',
    monetization_types: ['flatrate'],
    icon_url: 'https://images.justwatch.com/icon/52449861/s100',
  },
  {
    id: 356,
    name: 'wavve',
    monetization_types: ['flatrate', 'rent', 'buy'],
    icon_url: 'https://images.justwatch.com/icon/155655742/s100',
  },
  {
    id: 97,
    name: 'Watcha',
    monetization_types: ['flatrate'],
    icon_url: 'https://images.justwatch.com/icon/2538290/s100',
    icon_blur_hash: 'KPGlL@004n00%Mxu9Fofxu',
    slug: 'watcha',
  },
  {
    id: 96,
    name: 'Naver Store',
    monetization_types: ['buy', 'rent'],
    icon_url: 'https://images.justwatch.com/icon/2538289/s100',
  },
  {
    id: 3,
    name: 'Google Play Movies',
    monetization_types: ['rent', 'buy'],
    icon_url: 'https://images.justwatch.com/icon/169478387/s100',
  },
  {
    id: 11,
    name: 'Mubi',
    monetization_types: ['flatrate', 'rent'],
    icon_url: 'https://images.justwatch.com/icon/164970114/s100',
  },
  {
    id: 100,
    name: 'GuideDoc',
    monetization_types: ['flatrate'],
    icon_url: 'https://images.justwatch.com/icon/2625277/s100',
  },
  {
    id: 101,
    name: 'Daum',
    monetization_types: ['cinema'],
    icon_url: 'https://images.justwatch.com/icon/2655283/s100',
  },
  {
    id: 98,
    name: 'Megabox',
    monetization_types: ['cinema'],
    icon_url: 'https://images.justwatch.com/icon/2539917/s100',
  },
  {
    id: 283,
    name: 'Crunchyroll',
    monetization_types: ['flatrate'],
    icon_url: 'https://images.justwatch.com/icon/127445869/s100',
  },
  {
    id: 190,
    name: 'Curiosity Stream',
    monetization_types: ['flatrate'],
    icon_url: 'https://images.justwatch.com/icon/48600036/s100',
  },
  {
    id: 521,
    name: 'Spamflix',
    monetization_types: ['free', 'rent'],
    icon_url: 'https://images.justwatch.com/icon/240831409/s100',
  },
  {
    id: 475,
    name: 'DOCSVILLE',
    monetization_types: ['flatrate'],
    icon_url: 'https://images.justwatch.com/icon/208148387/s100',
  },
  {
    id: 495,
    name: 'CGood TV',
    monetization_types: ['free'],
    icon_url: 'https://images.justwatch.com/icon/208864843/s100',
  },
];

export const POSTERTITLEURL = `https://apis.justwatch.com/content/titles/ko_KR/popular?body=%7B%22fields%22:[%22id%22,%22title%22,%22full_path%22,%22poster%22,%22object_type%22],%22content_types%22:[%22movie%22],%22monetization_types%22:[%22ads%22,%22buy%22,%22flatrate%22,%22rent%22,%22free%22],%22page%22:40,%22page_size%22:40,%22matching_offers_only%22:false%7D`;
export const ICONURL = `https://images.justwatch.com/icon/8/s100/`;
