const GENREINFO = [
  {
    id: 1,
    short_name: 'act',
    technical_name: 'action',
    translation: '액션',
    slug: 'aegsyeon',
  },
  {
    id: 2,
    short_name: 'ani',
    technical_name: 'animation',
    translation: '애니메이션',
    slug: 'aenimeisyeon',
  },
  {
    id: 3,
    short_name: 'cmy',
    technical_name: 'comedy',
    translation: '코미디',
    slug: 'komidi',
  },
  {
    id: 4,
    short_name: 'crm',
    technical_name: 'crime',
    translation: '범죄',
    slug: 'beomjoe',
  },
  {
    id: 5,
    short_name: 'doc',
    technical_name: 'documentation',
    translation: '다큐멘터리',
    slug: 'dakyumenteori',
  },
  {
    id: 6,
    short_name: 'drm',
    technical_name: 'drama',
    translation: '드라마',
    slug: 'deurama',
  },
  {
    id: 7,
    short_name: 'fnt',
    technical_name: 'fantasy',
    translation: '판타지',
    slug: 'pantaji',
  },
  {
    id: 8,
    short_name: 'hst',
    technical_name: 'history',
    translation: '역사',
    slug: 'yeogsa',
  },
  {
    id: 9,
    short_name: 'hrr',
    technical_name: 'horror',
    translation: '공포',
    slug: 'gongpo',
  },
  {
    id: 10,
    short_name: 'fml',
    technical_name: 'family',
    translation: '가족',
    slug: 'gajog',
  },
  {
    id: 11,
    short_name: 'msc',
    technical_name: 'music',
    translation: '음악',
    slug: 'eumag',
  },
  {
    id: 12,
    short_name: 'trl',
    technical_name: 'thriller',
    translation: '스릴러',
    slug: 'seurilreo',
  },
  {
    id: 13,
    short_name: 'rma',
    technical_name: 'romance',
    translation: '로맨스',
    slug: 'romaenseu',
  },
  {
    id: 14,
    short_name: 'scf',
    technical_name: 'scifi',
    translation: 'SF',
    slug: 'sf',
  },
  {
    id: 15,
    short_name: 'spt',
    technical_name: 'sport',
    translation: '스포츠',
    slug: 'seupoceu',
  },
  {
    id: 16,
    short_name: 'war',
    technical_name: 'war',
    translation: '전쟁',
    slug: 'jeonjaeng',
  },
  {
    id: 17,
    short_name: 'wsn',
    technical_name: 'western',
    translation: '서부',
    slug: 'seobu',
  },
  {
    id: 23,
    short_name: 'rly',
    technical_name: 'reality',
    translation: 'Reality TV',
    slug: 'reality-tv',
  },
  {
    id: 18,
    short_name: 'eur',
    technical_name: 'european',
    translation: 'Made in Europe',
    slug: 'made-in-europe',
  },
];

const PLATFORMINFO = [
  {
    id: 8,
    technical_name: 'netflix',
    short_name: 'nfx',
    clear_name: 'Netflix',
    priority: 10,
    display_priority: 2,
    monetization_types: ['flatrate'],
    icon_url: '/icon/207360008/{profile}',
    icon_blur_hash: 'KVBJXFjt1^jto1a|A;a|,Z',
    slug: 'netflix',
    data: {
      deeplink_data: [
        {
          scheme: 'https',
          packages: [
            'com.netflix.ninja',
            'com.netflix.mediaclient',
            'com.netflix',
          ],
          platforms: ['fire_tv', 'android_tv', 'tvos', 'webos', 'tizenos'],
          path_template: 'www.netflix.com/watch/%DEEPLINK%',
          extras: { 'S.source': '30' },
        },
      ],
      packages: {
        android_tv: 'com.netflix.ninja',
        fire_tv: 'com.netflix.ninja',
        tvos: 'com.netflix.ninja',
        tizenos: 'com.netflix.ninja',
        webos: 'com.netflix.ninja',
      },
    },
  },
  {
    id: 119,
    technical_name: 'amazonprimevideo',
    short_name: 'prv',
    clear_name: 'Amazon Prime Video',
    priority: 5,
    display_priority: 3,
    monetization_types: ['flatrate'],
    icon_url: '/icon/52449861/{profile}',
    icon_blur_hash: 'KMQAQ@%M~Ux]WCjF~qj[IU',
    slug: 'amazon-prime-video',
    data: {
      deeplink_data: [
        {
          scheme: 'https',
          packages: ['com.amazon.avod'],
          platforms: ['fire_tv', 'tizenos', 'webos'],
          path_template:
            'watch.amazon.de/watch?asin=%DEEPLINK%\u0026contentType=MOVIE\u0026territory=DE\u0026ref_=atv_dp_pb_core',
          extras: null,
        },
        {
          scheme: '',
          packages: ['com.amazon.amazonvideo.livingroom'],
          platforms: ['android_tv'],
          path_template: '',
          extras: {
            'S.com.amazon.ignition.DeepLinkIntent.DEEP_LINK': '%DEEPLINK%',
          },
        },
        {
          scheme: '',
          packages: ['aiv'],
          platforms: ['tvos'],
          path_template: '',
          extras: null,
        },
      ],
      packages: {
        android_tv: 'com.amazon.amazonvideo.livingroom',
        fire_tv: 'com.amazon.avod',
        tvos: 'aiv',
        tizenos: 'com.amazon.avod',
        webos: 'com.amazon.avod',
      },
    },
  },
  {
    id: 356,
    technical_name: 'wavve',
    short_name: 'wav',
    clear_name: 'wavve',
    priority: 5,
    display_priority: 4,
    monetization_types: ['flatrate', 'rent', 'buy'],
    icon_url: '/icon/155655742/{profile}',
    icon_blur_hash: 'KtPQKwRo~mnie.kD_0WBD+',
    slug: 'wavve',
    data: {
      deeplink_data: [],
      packages: {
        android_tv: '',
        fire_tv: '',
        tvos: '',
        tizenos: '',
        webos: '',
      },
    },
  },
  {
    id: 97,
    technical_name: 'watcha',
    short_name: 'wac',
    clear_name: 'Watcha',
    priority: 5,
    display_priority: 5,
    monetization_types: ['flatrate'],
    icon_url: '/icon/2538290/{profile}',
    icon_blur_hash: 'KPGlL@004n00%Mxu9Fofxu',
    slug: 'watcha',
    data: {
      deeplink_data: [],
      packages: {
        android_tv: '',
        fire_tv: '',
        tvos: '',
        tizenos: '',
        webos: '',
      },
    },
  },
  {
    id: 96,
    technical_name: 'naverstore',
    short_name: 'nvs',
    clear_name: 'Naver Store',
    priority: 5,
    display_priority: 6,
    monetization_types: ['buy', 'rent'],
    icon_url: '/icon/2538289/{profile}',
    icon_blur_hash: 'KgDf|mkB5Nknj[a{0]ay=$',
    slug: 'naver-store',
    data: {
      deeplink_data: [],
      packages: {
        android_tv: '',
        fire_tv: '',
        tvos: '',
        tizenos: '',
        webos: '',
      },
    },
  },
  {
    id: 3,
    technical_name: 'play',
    short_name: 'ply',
    clear_name: 'Google Play Movies',
    priority: 4,
    display_priority: 7,
    monetization_types: ['rent', 'buy'],
    icon_url: '/icon/169478387/{profile}',
    icon_blur_hash: 'KSQ,j#Ac~XK#JB$S%MxBMe',
    slug: 'google-play-movies',
    data: {
      deeplink_data: [
        {
          scheme: 'https',
          packages: ['com.google.android.videos'],
          platforms: ['android_tv', 'fire_tv'],
          path_template: 'www.youtube.com/watch?v=%DEEPLINK%',
          extras: null,
        },
      ],
      packages: {
        android_tv: 'com.google.android.videos',
        fire_tv: 'com.google.android.videos',
        tvos: '',
        tizenos: '',
        webos: '',
      },
    },
  },
  {
    id: 11,
    technical_name: 'mubi',
    short_name: 'mbi',
    clear_name: 'Mubi',
    priority: 11,
    display_priority: 8,
    monetization_types: ['flatrate', 'rent'],
    icon_url: '/icon/164970114/{profile}',
    icon_blur_hash: 'KF5rQpoiRib2axj@9DWCt7',
    slug: 'mubi',
    data: {
      deeplink_data: [
        {
          scheme: '',
          packages: ['mubi'],
          platforms: ['fire_tv', 'android_tv', 'tvos', 'webos'],
          path_template: '',
          extras: null,
        },
      ],
      packages: {
        android_tv: 'mubi',
        fire_tv: 'mubi',
        tvos: 'mubi',
        tizenos: '',
        webos: 'mubi',
      },
    },
  },
  {
    id: 100,
    technical_name: 'guidedoc',
    short_name: 'gdc',
    clear_name: 'GuideDoc',
    priority: 5,
    display_priority: 9,
    monetization_types: ['flatrate'],
    icon_url: '/icon/2625277/{profile}',
    icon_blur_hash: 'KOB6fcS50NW?ayj[4=s:-n',
    slug: 'guidedoc',
    data: {
      deeplink_data: [],
      packages: {
        android_tv: '',
        fire_tv: '',
        tvos: '',
        tizenos: '',
        webos: '',
      },
    },
  },
  {
    id: 101,
    technical_name: 'daum',
    short_name: 'dam',
    clear_name: 'Daum',
    priority: 5,
    display_priority: 10,
    monetization_types: ['cinema'],
    icon_url: '/icon/2655283/{profile}',
    icon_blur_hash: 'KSR.}pW0_NKkW=#k?ws%IU',
    slug: 'daum',
    data: {
      deeplink_data: [],
      packages: {
        android_tv: '',
        fire_tv: '',
        tvos: '',
        tizenos: '',
        webos: '',
      },
    },
  },
  {
    id: 98,
    technical_name: 'megabox',
    short_name: 'mbx',
    clear_name: 'Megabox',
    priority: 5,
    display_priority: 11,
    monetization_types: ['cinema'],
    icon_url: '/icon/2539917/{profile}',
    icon_blur_hash: 'KIRMe]xv?a%Mjaj[?@oeMz',
    slug: 'megabox',
    data: {
      deeplink_data: [],
      packages: {
        android_tv: '',
        fire_tv: '',
        tvos: '',
        tizenos: '',
        webos: '',
      },
    },
  },
  {
    id: 283,
    technical_name: 'crunchyroll',
    short_name: 'cru',
    clear_name: 'Crunchyroll',
    priority: 5,
    display_priority: 12,
    monetization_types: ['flatrate'],
    icon_url: '/icon/127445869/{profile}',
    icon_blur_hash: 'KjSD4wozQRn$kCj]UvaKpJ',
    slug: 'crunchyroll',
    data: {
      deeplink_data: [
        {
          scheme: '',
          packages: ['crunchyroll'],
          platforms: ['fire_tv', 'android_tv', 'tvos'],
          path_template: '',
          extras: null,
        },
      ],
      packages: {
        android_tv: 'crunchyroll',
        fire_tv: 'crunchyroll',
        tvos: 'crunchyroll',
        tizenos: '',
        webos: '',
      },
    },
  },
  {
    id: 190,
    technical_name: 'curiositystream',
    short_name: 'cts',
    clear_name: 'Curiosity Stream',
    priority: 5,
    display_priority: 13,
    monetization_types: ['flatrate'],
    icon_url: '/icon/48600036/{profile}',
    icon_blur_hash: 'KjS#6LoeiHn#fQkCU[f6em',
    slug: 'curiosity-stream',
    data: {
      deeplink_data: [
        {
          scheme: '',
          packages: ['curiositystream'],
          platforms: ['android_tv', 'fire_tv', 'tvos', 'webos', 'tizenos'],
          path_template: '',
          extras: null,
        },
      ],
      packages: {
        android_tv: 'curiositystream',
        fire_tv: 'curiositystream',
        tvos: 'curiositystream',
        tizenos: 'curiositystream',
        webos: 'curiositystream',
      },
    },
  },
  {
    id: 521,
    technical_name: 'spamflix',
    short_name: 'sfx',
    clear_name: 'Spamflix',
    priority: 5,
    display_priority: 100,
    monetization_types: ['free', 'rent'],
    icon_url: '/icon/240831409/{profile}',
    icon_blur_hash: 'KY1hy+fjU[cOfRilbBfPjf',
    slug: 'spamflix',
    data: {
      deeplink_data: [],
      packages: {
        android_tv: '',
        fire_tv: '',
        tvos: '',
        tizenos: '',
        webos: '',
      },
    },
  },
  {
    id: 475,
    technical_name: 'docsville',
    short_name: 'dsv',
    clear_name: 'DOCSVILLE',
    priority: 5,
    display_priority: 1001,
    monetization_types: ['flatrate'],
    icon_url: '/icon/208148387/{profile}',
    icon_blur_hash: 'KFS=u7xuuPxuj[bHuOaenj',
    slug: 'docsville',
    data: {
      deeplink_data: [],
      packages: {
        android_tv: '',
        fire_tv: '',
        tvos: '',
        tizenos: '',
        webos: '',
      },
    },
  },
  {
    id: 495,
    technical_name: 'cgoodtv',
    short_name: 'cgt',
    clear_name: 'CGood TV',
    priority: 5,
    display_priority: 1001,
    monetization_types: ['free'],
    icon_url: '/icon/208864843/{profile}',
    icon_blur_hash: 'KARbbt-_hg-wjbnOhfnOaK',
    slug: 'cgood-tv',
    data: {
      deeplink_data: [],
      packages: {
        android_tv: '',
        fire_tv: '',
        tvos: '',
        tizenos: '',
        webos: '',
      },
    },
  },
];
export const POSTERTITLEURL = `https://apis.justwatch.com/content/titles/ko_KR/popular?body=%7B%22fields%22:[%22id%22,%22title%22,%22full_path%22,%22poster%22,%22object_type%22],%22content_types%22:[%22movie%22],%22monetization_types%22:[%22ads%22,%22buy%22,%22flatrate%22,%22rent%22,%22free%22],%22page%22:40,%22page_size%22:40,%22matching_offers_only%22:false%7D`;
export const POSTERURL =
  'https://images.justwatch.com/poster/${posterId}/s332/';
